version: "3.7"
services:
  db:
    image: "mysql:8.0.36"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234abjd
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234abjd
        - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/run/mysqld
    logging:
            driver: none
    ports:
      - "33061:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - node.name=chat-app-node-1
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        timeout: 5s
        retries: 10
  redis:
    image: redis:7.0.2-bullseye
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
      driver: none
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 5s
      retries: 10
  sidekiq:
    build: ./
    command: bundle exec sidekiq
    restart: always
    volumes:
      - ./:/workspace
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 1234abjd
      DB_NAME: chatting_app_development
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - "db"
      - "web"
      - "redis"
      - "elasticsearch"
  web:
    build: .
    command: "./bin/rails server --binding 0.0.0.0"
    restart: always
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 1234abjd
      DB_NAME: chatting_app_development
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    volumes:
      - ./:/workspace
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
volumes:
  db:
  bundle:
  elasticsearch:
  redis: